language: node_js

node_js:
- "4"

sudo: false
env:
  global:
    - REGION=us
    - APPID=QvNM6AG2khJtBQo6WRMWqfLV-gzGzoHsz
    - APPKEY=be2YmUduiuEnCB2VR9bLRnnV
    - MASTERKEY=1AqFJWElESSui6JKqHiKnLTY
    - HOOKKEY=Y7RVPi20qOKQg4Lp8CyY35Lq
    - STATUS_TARGET_USER_ID=57d7b3c28a51a2004eb9b31d
    - FILE_ID=577258d732070000567dea7e
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm; fi
install:
  - npm install -g codecov
  - npm install
script:
  - npm test && codecov
  - npm run build
after_success:
  - if [[ "$TRAVIS_BRANCH" == "v2" ]] && [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
      ./script/release.sh;
    fi
